### ISSUE TITLE
http error in cellxgene 16,02 (docker)

### ISSUE THREAD

**Issue by wariobrega** [chanzuckerberg/cellxgene#1797]
Hello everyone,

I am trying to load a .h5ad with a lot of columns (all categorical).

However, I get an http error when I try to load cellxgene (see screenshot attached).

![cellxgene_error](https://user-images.githubusercontent.com/10073781/91316102-be3eb200-e7b8-11ea-9344-1cd78df6068a.png)

This issue already occurred to me with 16.02 on a smaller dataset and  I found that it was an issue with a single column that had to be renamed and reparsed (i.e.: changing the column name to "**Cluster** rather than "**Orig_Cluster**" and changing the values from **Cluster_X** to **X** )

I wonder whether this is an issue that occurred only to me or it is a known bug.

PS: I am running cellXgene in a docker container 

Cheers,

Daniele

**Comment by maniarathi** [comment]
Hi @wariobrega ! Thank you so much for reporting the bug. Just a couple questions: what command are you using to launch cellxgene? (Wondering if you are making use of the any flag options, or if this is the vanilla launch). Also, do you have NaNs in any of your categories?

**Comment by maniarathi** [comment]
Hi @wariobrega ! We released version 0.16.4 this past Friday -- would you be able to please take a look to see if the issue still persists? Thank you!

**Comment by wariobrega** [comment]
Hi @maniarathi and sorry for the late reply, I was out of office.

First of all, the command I'm using to launch cellxgene is the following:

> docker run \
> -v $DATADIR \
 > -v $ANNOTSDIR \
> -p 37004:37004 \
> cellxgene0.16.4 launch \
> --verbose
> --host 0.0.0.0 \
> --port 37004 \
> --title MYTITLE \
> --annotations-dir annots 
> $H5ADFILE

where `$DATADIR` and `$ANNOTDIR`  in the `-v` Docker argument are the path to a directory storing the data and the annotations, respectively.

I also used here the 16.04 version (just pulled) and the `--verbose flag` and I obtain the following output from Terminal.

![image](https://user-images.githubusercontent.com/10073781/91837664-99c95680-ec4c-11ea-95f9-cc6ae150a84f.png)

As for the **NaNs** there are present in the .h5ad object, but I think the problem is not there. I had the same issue with another .h5ad not storing any NaN, and I solved it by finding the "problematic" column and renaming/refactor it (removing whitespaces in column value, renaming the column using pandas.

Hope this helps!

Daniele

**Comment by maniarathi** [comment]
Thank you for the additional information! We're taking a look!

**Comment by MDunitz** [comment]
Steps to reproduce
- create docker image from 0.16.4
` docker build . cellxgene:0.16.4      
`
- run docker
`docker run --name dunitz-test7 -v "$(pwd)/datadir":/datadir -v $ANNOTSDIR -p 37004:37004 cellxgene:0.16.4 launch --open --verbose  --host 0.0.0.0 --port 37004 --title MYTITLE --annotations-dir annots datadir/krasnow_lab_human_lung_cell_atlas_smartseq2-2-remixed.h5ad`

test w/ .cxg and .h5ad
works fine with .cxg just hangs with .h5ad

**Comment by MDunitz** [comment]
Hi @wariobrega 
I'm working on investigating the cause of the bug. Could I take a look at the dataset you are working with? or Could you try converting it to the cxg format? You can use the cellxgene cli `cellxgene convert INPUT_FILE` and then try launching cellxgene with the cxg file.
Thanks!

**Comment by wariobrega** [comment]
Hi @maniarathi! I don't know whether I can share this data with you, I'll have to ask my supervisor for this kind of permission. 

I'll get back to you and I'll let you know ASAP

Cheers,

Daniele

**Comment by MDunitz** [comment]
No worries if you cant. 
Just let me know if you are able to run it with the h5ad file converted to a cxg

**Comment by wariobrega** [comment]
hi @MDunitz ,

I tried converting the .h5ad to .cxg using cellxgene convert (both using te docker machine and a standard pip installation).

However, I get the following error on ANY .h5ad file (screenshot attached)

![image](https://user-images.githubusercontent.com/10073781/92279038-b4bef380-eef6-11ea-895e-a9c288d3f72d.png)

Am I getting something wrong?

**Comment by MDunitz** [comment]
You arent doing anything wrong, the script is just expecting a particular schema. Can you try passing in the flag  `--disable-corpora-schema`

**Comment by wariobrega** [comment]
Done, except I still obtain an error: (see screenshot with command and error)

(the --disable-custom-colors was added just to get rid of the warning, the error stays the same)

![image](https://user-images.githubusercontent.com/10073781/92512091-90248d80-f20e-11ea-935c-290d7468f5bf.png)

**Comment by MDunitz** [comment]
hmm thats interesting. Were you able to speak with your supervisor about giving me access to the dataset for debugging purposes? or would you be open to doing a zoom call and sharing your screen with me? Also would it be possible for you to send me to the console error output from the original http error?

**Comment by wariobrega** [comment]
Hi @MDunitz, I spoke to my supervisor and he advised me to share the data only upon a written agreement on not sharing/not using the data (I don't know if you already experienced this already and we can set up some paperwork).

Otherwise let's plan a zoom call and I'll show you the issue live.

As for the cellxgene launch console output, I have relaunched the dataset using the --debug mode (outside the docker image) and I attach you here the console output:
[cellxgene_debuglog.txt](https://github.com/chanzuckerberg/cellxgene/files/5195883/cellxgene_debuglog.txt)

**Comment by MDunitz** [comment]
@wariobrega
Happy to sign the written agreement, let's set up a zoom call first. Just to double check you still get the error when you pass in the `--disable-custom-colors` flag?
Should I use the email on your git profile for the calendar event?

**Comment by wariobrega** [comment]
@MDunitz yes, I can confirm that I still got the error with the `--disable-custom-colors` flag.

Let's set up the zoom call, I kindly ask you to use daniele.capocefalo@ieo.it as calendar mail. If this doesn't help, let's discuss the agreement ;)

Cheers,

Daniele

**Comment by MDunitz** [comment]
@wariobrega just sent an invite. Let me know if that time doesnt work.

**Comment by MDunitz** [comment]
Notes from Sept 17th
- dataset giving him trouble is a projection via [scanpy bbknn](https://scanpy-tutorials.readthedocs.io/en/latest/integrating-data-using-ingest.html)  (integrating datasets)
- their datasets has been analyzed/cast through several times (with different parameters/combinations) trying to subcluster/recluster groups of cells to find subtle differences
- other dataset is Regev
- lots of nans bc of differences between datasets

- one column name had a slash, tried dropping it, converting to h5ad  and then launching cellxgene. Ran into http errors via `cellxgene launch` and when launching via docker.

When we converted the h5ad (without the column name containing a slash) -> cxg we were able to successfully launch cellxgene with the cxg dataset 

We have a ticket filed for the underlying bug with the h5ad conversion when calling launch. -- https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/cellxgene/1849
